Shader "KSP2/Planets/Local"
{
    Properties {
        _AlbedoScaledTex ("Scaled-space Albedo Map (RGB)", 2D) = "white" {}
        _AlbedoScaledFadeParams ("Scaled-space Albedo Fade Params", Vector) = (0,20000,0.5,1)
        _NormalScaledTex ("Scaled-space Normal Map", 2D) = "bump" {}
        _NormalScaledFadeParams ("Scaled-space Normal Fade Params", Vector) = (0,20000,0.5,1)
        _PackedScaledTex ("Scaled-space Packed Map (Metallic, Occlusion, Emission, Smoothness)", 2D) = "black" {}
        _PackedScaledFadeParams ("Scaled-space Packed Fade Params", Vector) = (0,20000,0.5,1)
        _EmissionScaledTex ("Scaled-space Emission Map", 2D) = "black" {}
        _EmissionScaledFadeParams ("Scaled-space Emission Fade Params", Vector) = (0,20000,0.5,1)
        _EmissionScale ("Scaled-space Emission Scale", Range(0, 20)) = 0
        _Transition ("Transition", Float) = 0
        _BiomeMaskTex ("Biome Mask Map", 2D) = "red" {}
        _BiomeCutoffs ("Biome Cutoffs", Vector) = (0,0,0,0)
        _SubzoneMaskTex ("Subzone Mask Map", 2D) = "white" {}
        _GlobalGradienceTex ("Global Gradience Map", 2D) = "black" {}
        _GlobalCurvatureTex ("Global Curvature Map", 2D) = "black" {}
        _LargeHeightMapUVScales ("Large Grad Map UV Scales", Vector) = (1,1,1,1)
        _MediumHeightMapUVScales ("Medium Grad Map UV Scales", Vector) = (1,1,1,1)
        _Subzone3HeightMapUVScales ("Subzone 3 Grad Map UV Scales", Vector) = (1,1,1,1)
        _Subzone4HeightMapUVScales ("Subzone 4 Grad Map UV Scales", Vector) = (1,1,1,1)
        _TriplanarContrast ("Triplanar Contrast", Range(1, 8)) = 4
        _TriplanarUVScaleOffset ("Triplanar UV Scale/Offset", Vector) = (1,1,0,0)
        _SubZonesNormalTextureArray ("Sub Zones Normal Array", 2DArray) = "bump" {}
        _Subzone1NormalIndices ("Subzone 1 Normal Array Indices", Vector) = (-1,-1,-1,-1)
        _Subzone2NormalIndices ("Subzone 2 Normal Array Indices", Vector) = (-1,-1,-1,-1)
        _Subzone3NormalIndices ("Subzone 3 Normal Array Indices", Vector) = (-1,-1,-1,-1)
        _Subzone4NormalIndices ("Subzone 4 Normal Array Indices", Vector) = (-1,-1,-1,-1)
        _LargeCurvatureR ("Large Curvature R", 2D) = "black" {}
        _LargeCurvatureG ("Large Curvature G", 2D) = "black" {}
        _LargeCurvatureB ("Large Curvature B", 2D) = "black" {}
        _LargeCurvatureA ("Large Curvature A", 2D) = "black" {}
        _LargeGradienceR ("Large Gradience R", 2D) = "black" {}
        _LargeGradienceG ("Large Gradience G", 2D) = "black" {}
        _LargeGradienceB ("Large Gradience B", 2D) = "black" {}
        _LargeGradienceA ("Large Gradience A", 2D) = "black" {}
        _LargeNormalR ("Large Normal R", 2D) = "bump" {}
        _LargeNormalG ("Large Normal G", 2D) = "bump" {}
        _LargeNormalB ("Large Normal B", 2D) = "bump" {}
        _LargeNormalA ("Large Normal A", 2D) = "bump" {}
        _LargeNormalRUVParams ("Large Normal R UV Params", Vector) = (1,1,0,0)
        _LargeNormalGUVParams ("Large Normal G UV Params", Vector) = (1,1,0,0)
        _LargeNormalBUVParams ("Large Normal B UV Params", Vector) = (1,1,0,0)
        _LargeNormalAUVParams ("Large Normal A UV Params", Vector) = (1,1,0,0)
        _LargeNormalRFadeParams ("Large Normal R Fade Params", Vector) = (0,10000,0.5,1)
        _LargeNormalGFadeParams ("Large Normal G Fade Params", Vector) = (0,10000,0.5,1)
        _LargeNormalBFadeParams ("Large Normal B Fade Params", Vector) = (0,10000,0.5,1)
        _LargeNormalAFadeParams ("Large Normal A Fade Params", Vector) = (0,10000,0.5,1)
        _LargeRSubzoneFilter ("Large R Subzone Filter", Vector) = (1,1,1,1)
        _LargeGSubzoneFilter ("Large G Subzone Filter", Vector) = (1,1,1,1)
        _LargeBSubzoneFilter ("Large B Subzone Filter", Vector) = (1,1,1,1)
        _LargeASubzoneFilter ("Large A Subzone Filter", Vector) = (1,1,1,1)
        _MidCurvatureR ("Mid Curvature R", 2D) = "black" {}
        _MidCurvatureG ("Mid Curvature G", 2D) = "black" {}
        _MidCurvatureB ("Mid Curvature B", 2D) = "black" {}
        _MidCurvatureA ("Mid Curvature A", 2D) = "black" {}
        _MidGradienceR ("Mid Gradience R", 2D) = "black" {}
        _MidGradienceG ("Mid Gradience G", 2D) = "black" {}
        _MidGradienceB ("Mid Gradience B", 2D) = "black" {}
        _MidGradienceA ("Mid Gradience A", 2D) = "black" {}
        _MidNormalR ("Mid Normal R", 2D) = "bump" {}
        _MidNormalG ("Mid Normal G", 2D) = "bump" {}
        _MidNormalB ("Mid Normal B", 2D) = "bump" {}
        _MidNormalA ("Mid Normal A", 2D) = "bump" {}
        _MidNormalRUVParams ("Mid Normal R UV Params", Vector) = (1,1,0,0)
        _MidNormalGUVParams ("Mid Normal G UV Params", Vector) = (1,1,0,0)
        _MidNormalBUVParams ("Mid Normal B UV Params", Vector) = (1,1,0,0)
        _MidNormalAUVParams ("Mid Normal A UV Params", Vector) = (1,1,0,0)
        _MidNormalRFadeParams ("Mid Normal R Fade Params", Vector) = (0,10000,0.5,1)
        _MidNormalGFadeParams ("Mid Normal G Fade Params", Vector) = (0,10000,0.5,1)
        _MidNormalBFadeParams ("Mid Normal B Fade Params", Vector) = (0,10000,0.5,1)
        _MidNormalAFadeParams ("Mid Normal A Fade Params", Vector) = (0,10000,0.5,1)
        _MidRSubzoneFilter ("Mid R Subzone Filter", Vector) = (1,1,1,1)
        _MidGSubzoneFilter ("Mid G Subzone Filter", Vector) = (1,1,1,1)
        _MidBSubzoneFilter ("Mid B Subzone Filter", Vector) = (1,1,1,1)
        _MidASubzoneFilter ("Mid A Subzone Filter", Vector) = (1,1,1,1)
        _Subzone3CurvatureR ("Subzone 3 Curvature R", 2D) = "black" {}
        _Subzone3CurvatureG ("Subzone 3 Curvature G", 2D) = "black" {}
        _Subzone3CurvatureB ("Subzone 3 Curvature B", 2D) = "black" {}
        _Subzone3CurvatureA ("Subzone 3 Curvature A", 2D) = "black" {}
        _Subzone3GradienceR ("Subzone 3 Gradience R", 2D) = "black" {}
        _Subzone3GradienceG ("Subzone 3 Gradience G", 2D) = "black" {}
        _Subzone3GradienceB ("Subzone 3 Gradience B", 2D) = "black" {}
        _Subzone3GradienceA ("Subzone 3 Gradience A", 2D) = "black" {}
        _Subzone3NormalR ("Subzone 3 Normal R", 2D) = "bump" {}
        _Subzone3NormalG ("Subzone 3 Normal G", 2D) = "bump" {}
        _Subzone3NormalB ("Subzone 3 Normal B", 2D) = "bump" {}
        _Subzone3NormalA ("Subzone 3 Normal A", 2D) = "bump" {}
        _Subzone3NormalRUVParams ("Subzone 3 Normal R UV Params", Vector) = (1,1,0,0)
        _Subzone3NormalGUVParams ("Subzone 3 Normal G UV Params", Vector) = (1,1,0,0)
        _Subzone3NormalBUVParams ("Subzone 3 Normal B UV Params", Vector) = (1,1,0,0)
        _Subzone3NormalAUVParams ("Subzone 3 Normal A UV Params", Vector) = (1,1,0,0)
        _Subzone3NormalRFadeParams ("Subzone 3 Normal R Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone3NormalGFadeParams ("Subzone 3 Normal G Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone3NormalBFadeParams ("Subzone 3 Normal B Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone3NormalAFadeParams ("Subzone 3 Normal A Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone3RSubzoneFilter ("Global3 R Subzone Filter", Vector) = (1,1,1,1)
        _Subzone3GSubzoneFilter ("Global3 G Subzone Filter", Vector) = (1,1,1,1)
        _Subzone3BSubzoneFilter ("Global3 B Subzone Filter", Vector) = (1,1,1,1)
        _Subzone3ASubzoneFilter ("Global3 A Subzone Filter", Vector) = (1,1,1,1)
        _Subzone4CurvatureR ("Subzone 4 Curvature R", 2D) = "black" {}
        _Subzone4CurvatureG ("Subzone 4 Curvature G", 2D) = "black" {}
        _Subzone4CurvatureB ("Subzone 4 Curvature B", 2D) = "black" {}
        _Subzone4CurvatureA ("Subzone 4 Curvature A", 2D) = "black" {}
        _Subzone4GradienceR ("Subzone 4 Gradience R", 2D) = "black" {}
        _Subzone4GradienceG ("Subzone 4 Gradience G", 2D) = "black" {}
        _Subzone4GradienceB ("Subzone 4 Gradience B", 2D) = "black" {}
        _Subzone4GradienceA ("Subzone 4 Gradience A", 2D) = "black" {}
        _Subzone4NormalR ("Subzone 4 Normal R", 2D) = "bump" {}
        _Subzone4NormalG ("Subzone 4 Normal G", 2D) = "bump" {}
        _Subzone4NormalB ("Subzone 4 Normal B", 2D) = "bump" {}
        _Subzone4NormalA ("Subzone 4 Normal A", 2D) = "bump" {}
        _Subzone4NormalRUVParams ("Subzone 4 Normal R UV Params", Vector) = (1,1,0,0)
        _Subzone4NormalGUVParams ("Subzone 4 Normal G UV Params", Vector) = (1,1,0,0)
        _Subzone4NormalBUVParams ("Subzone 4 Normal B UV Params", Vector) = (1,1,0,0)
        _Subzone4NormalAUVParams ("Subzone 4 Normal A UV Params", Vector) = (1,1,0,0)
        _Subzone4NormalRFadeParams ("Subzone 4 Normal R Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone4NormalGFadeParams ("Subzone 4 Normal G Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone4NormalBFadeParams ("Subzone 4 Normal B Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone4NormalAFadeParams ("Subzone 4 Normal A Fade Params", Vector) = (0,10000,0.5,1)
        _Subzone4RSubzoneFilter ("Global4 R Subzone Filter", Vector) = (1,1,1,1)
        _Subzone4GSubzoneFilter ("Global4 G Subzone Filter", Vector) = (1,1,1,1)
        _Subzone4BSubzoneFilter ("Global4 B Subzone Filter", Vector) = (1,1,1,1)
        _Subzone4ASubzoneFilter ("Global4 A Subzone Filter", Vector) = (1,1,1,1)
        _Radius ("Sphere Radius", Float) = 0
        _SmallAlbedoArray ("Small Albedo Array", 2DArray) = "white" {}
        _SmallNormalArray ("Small Normal Array", 2DArray) = "bump" {}
        _SmallMetalArray ("Small Metal Array", 2DArray) = "white" {}
        _DecalAlbedo ("Decal Albedo", 2DArray) = "white" {}
        _DecalNormalSAO ("Decal Normal SAO", 2DArray) = "bump" {}
        _DecalControl ("Decal Control", 2D) = "black" {}
        _DecalStaticData ("Decal Static Data", 2D) = "black" {}
        _DecalFadeParams ("Decal Fade Params", Vector) = (0,20000,1,0)
        _SmallBiomeR ("Small Biome R", Vector) = (-1,-1,-1,-1)
        _SmallBiomeG ("Small Biome G", Vector) = (-1,-1,-1,-1)
        _SmallBiomeB ("Small Biome B", Vector) = (-1,-1,-1,-1)
        _SmallBiomeA ("Small Biome A", Vector) = (-1,-1,-1,-1)
        _SmallHeightWeightR ("Small Height Weight R", Vector) = (0,0,0,0)
        _SmallHeightWeightG ("Small Height Weight G", Vector) = (0,0,0,0)
        _SmallHeightWeightB ("Small Height Weight B", Vector) = (0,0,0,0)
        _SmallHeightWeightA ("Small Height Weight A", Vector) = (0,0,0,0)
        _SmallWeightSoftnessR ("Small Height Weight Softness R", Vector) = (0,0,0,0)
        _SmallWeightSoftnessG ("Small Height Weight Softness G", Vector) = (0,0,0,0)
        _SmallWeightSoftnessB ("Small Height Weight Softness B", Vector) = (0,0,0,0)
        _SmallWeightSoftnessA ("Small Height Weight Softness A", Vector) = (0,0,0,0)
        _SmallBiomeHeightEnableR ("Small Biome R Height Enable", Vector) = (0,0,0,0)
        _SmallBiomeRHeightParams1 ("Small Biome R Height Params 1", Vector) = (0,0,0,0)
        _SmallBiomeRHeightParams2 ("Small Biome R Height Params 2", Vector) = (0,0,0,0)
        _SmallBiomeRHeightParams3 ("Small Biome R Height Params 3", Vector) = (0,0,0,0)
        _SmallBiomeRHeightParams4 ("Small Biome R Height Params 4", Vector) = (0,0,0,0)
        _SmallBiomeHeightEnableG ("Small Biome G Height Enable", Vector) = (0,0,0,0)
        _SmallBiomeGHeightParams1 ("Small Biome G Height Params 1", Vector) = (0,0,0,0)
        _SmallBiomeGHeightParams2 ("Small Biome G Height Params 2", Vector) = (0,0,0,0)
        _SmallBiomeGHeightParams3 ("Small Biome G Height Params 3", Vector) = (0,0,0,0)
        _SmallBiomeGHeightParams4 ("Small Biome G Height Params 4", Vector) = (0,0,0,0)
        _SmallBiomeHeightEnableB ("Small Biome B Height Enable", Vector) = (0,0,0,0)
        _SmallBiomeBHeightParams1 ("Small Biome B Height Params 1", Vector) = (0,0,0,0)
        _SmallBiomeBHeightParams2 ("Small Biome B Height Params 2", Vector) = (0,0,0,0)
        _SmallBiomeBHeightParams3 ("Small Biome B Height Params 3", Vector) = (0,0,0,0)
        _SmallBiomeBHeightParams4 ("Small Biome B Height Params 4", Vector) = (0,0,0,0)
        _SmallBiomeHeightEnableA ("Small Biome A Height Enable", Vector) = (0,0,0,0)
        _SmallBiomeAHeightParams1 ("Small Biome A Height Params 1", Vector) = (0,0,0,0)
        _SmallBiomeAHeightParams2 ("Small Biome A Height Params 2", Vector) = (0,0,0,0)
        _SmallBiomeAHeightParams3 ("Small Biome A Height Params 3", Vector) = (0,0,0,0)
        _SmallBiomeAHeightParams4 ("Small Biome A Height Params 4", Vector) = (0,0,0,0)
        _SmallBiomeSlopeEnableR ("Small Biome R Slope Enable", Vector) = (0,0,0,0)
        _SmallBiomeRSlopeParams1 ("Small Biome R Slope Params 1", Vector) = (0,0,0,0)
        _SmallBiomeRSlopeParams2 ("Small Biome R Slope Params 2", Vector) = (0,0,0,0)
        _SmallBiomeRSlopeParams3 ("Small Biome R Slope Params 3", Vector) = (0,0,0,0)
        _SmallBiomeRSlopeParams4 ("Small Biome R Slope Params 4", Vector) = (0,0,0,0)
        _SmallBiomeRGradMapWeights1 ("Small Biome R Gradient Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeRGradMapWeights2 ("Small Biome R Gradient Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeRGradMapWeights3 ("Small Biome R Gradient Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeRGradMapWeights4 ("Small Biome R Gradient Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomeSlopeEnableG ("Small Biome G Slope Enable", Vector) = (0,0,0,0)
        _SmallBiomeGSlopeParams1 ("Small Biome G Slope Params 1", Vector) = (0,0,0,0)
        _SmallBiomeGSlopeParams2 ("Small Biome G Slope Params 2", Vector) = (0,0,0,0)
        _SmallBiomeGSlopeParams3 ("Small Biome G Slope Params 3", Vector) = (0,0,0,0)
        _SmallBiomeGSlopeParams4 ("Small Biome G Slope Params 4", Vector) = (0,0,0,0)
        _SmallBiomeGGradMapWeights1 ("Small Biome G Gradient Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeGGradMapWeights2 ("Small Biome G Gradient Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeGGradMapWeights3 ("Small Biome G Gradient Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeGGradMapWeights4 ("Small Biome G Gradient Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomeSlopeEnableB ("Small Biome B Slope Enable", Vector) = (0,0,0,0)
        _SmallBiomeBSlopeParams1 ("Small Biome B Slope Params 1", Vector) = (0,0,0,0)
        _SmallBiomeBSlopeParams2 ("Small Biome B Slope Params 2", Vector) = (0,0,0,0)
        _SmallBiomeBSlopeParams3 ("Small Biome B Slope Params 3", Vector) = (0,0,0,0)
        _SmallBiomeBSlopeParams4 ("Small Biome B Slope Params 4", Vector) = (0,0,0,0)
        _SmallBiomeBGradMapWeights1 ("Small Biome B Gradient Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeBGradMapWeights2 ("Small Biome B Gradient Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeBGradMapWeights3 ("Small Biome B Gradient Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeBGradMapWeights4 ("Small Biome B Gradient Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomeSlopeEnableA ("Small Biome A Slope Enable", Vector) = (0,0,0,0)
        _SmallBiomeASlopeParams1 ("Small Biome A Slope Params 1", Vector) = (0,0,0,0)
        _SmallBiomeASlopeParams2 ("Small Biome A Slope Params 2", Vector) = (0,0,0,0)
        _SmallBiomeASlopeParams3 ("Small Biome A Slope Params 3", Vector) = (0,0,0,0)
        _SmallBiomeASlopeParams4 ("Small Biome A Slope Params 4", Vector) = (0,0,0,0)
        _SmallBiomeAGradMapWeights1 ("Small Biome A Gradient Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeAGradMapWeights2 ("Small Biome A Gradient Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeAGradMapWeights3 ("Small Biome A Gradient Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeAGradMapWeights4 ("Small Biome A Gradient Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomePeakCavEnableR ("Small Biome R Peak/Cavity Enable", Vector) = (0,0,0,0)
        _SmallBiomeRPeakCavParams1 ("Small Biome R Peak/Cavity Params 1", Vector) = (0,0,0,0)
        _SmallBiomeRPeakCavParams2 ("Small Biome R Peak/Cavity Params 2", Vector) = (0,0,0,0)
        _SmallBiomeRPeakCavParams3 ("Small Biome R Peak/Cavity Params 3", Vector) = (0,0,0,0)
        _SmallBiomeRPeakCavParams4 ("Small Biome R Peak/Cavity Params 4", Vector) = (0,0,0,0)
        _SmallBiomeRCurvMapWeights1 ("Small Biome R Curvature Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeRCurvMapWeights2 ("Small Biome R Curvature Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeRCurvMapWeights3 ("Small Biome R Curvature Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeRCurvMapWeights4 ("Small Biome R Curvature Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomePeakCavEnableG ("Small Biome G Peak/Cavity Enable", Vector) = (0,0,0,0)
        _SmallBiomeGPeakCavParams1 ("Small Biome G Peak/Cavity Params 1", Vector) = (0,0,0,0)
        _SmallBiomeGPeakCavParams2 ("Small Biome G Peak/Cavity Params 2", Vector) = (0,0,0,0)
        _SmallBiomeGPeakCavParams3 ("Small Biome G Peak/Cavity Params 3", Vector) = (0,0,0,0)
        _SmallBiomeGPeakCavParams4 ("Small Biome G Peak/Cavity Params 4", Vector) = (0,0,0,0)
        _SmallBiomeGCurvMapWeights1 ("Small Biome G Curvature Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeGCurvMapWeights2 ("Small Biome G Curvature Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeGCurvMapWeights3 ("Small Biome G Curvature Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeGCurvMapWeights4 ("Small Biome G Curvature Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomePeakCavEnableB ("Small Biome B Peak/Cavity Enable", Vector) = (0,0,0,0)
        _SmallBiomeBPeakCavParams1 ("Small Biome B Peak/Cavity Params 1", Vector) = (0,0,0,0)
        _SmallBiomeBPeakCavParams2 ("Small Biome B Peak/Cavity Params 2", Vector) = (0,0,0,0)
        _SmallBiomeBPeakCavParams3 ("Small Biome B Peak/Cavity Params 3", Vector) = (0,0,0,0)
        _SmallBiomeBPeakCavParams4 ("Small Biome B Peak/Cavity Params 4", Vector) = (0,0,0,0)
        _SmallBiomeBCurvMapWeights1 ("Small Biome B Curvature Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeBCurvMapWeights2 ("Small Biome B Curvature Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeBCurvMapWeights3 ("Small Biome B Curvature Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeBCurvMapWeights4 ("Small Biome B Curvature Map Weights 4", Vector) = (1,1,1,1)
        _SmallBiomePeakCavEnableA ("Small Biome A Peak/Cavity Enable", Vector) = (0,0,0,0)
        _SmallBiomeAPeakCavParams1 ("Small Biome A Peak/Cavity Params 1", Vector) = (0,0,0,0)
        _SmallBiomeAPeakCavParams2 ("Small Biome A Peak/Cavity Params 2", Vector) = (0,0,0,0)
        _SmallBiomeAPeakCavParams3 ("Small Biome A Peak/Cavity Params 3", Vector) = (0,0,0,0)
        _SmallBiomeAPeakCavParams4 ("Small Biome A Peak/Cavity Params 4", Vector) = (0,0,0,0)
        _SmallBiomeACurvMapWeights1 ("Small Biome A Curvature Map Weights 1", Vector) = (1,1,1,1)
        _SmallBiomeACurvMapWeights2 ("Small Biome A Curvature Map Weights 2", Vector) = (1,1,1,1)
        _SmallBiomeACurvMapWeights3 ("Small Biome A Curvature Map Weights 3", Vector) = (1,1,1,1)
        _SmallBiomeACurvMapWeights4 ("Small Biome A Curvature Map Weights 4", Vector) = (1,1,1,1)
        _SmallUVScaleR ("Small UV Scale R", Vector) = (1,1,1,1)
        _SmallUVScaleG ("Small UV Scale G", Vector) = (1,1,1,1)
        _SmallUVScaleB ("Small UV Scale B", Vector) = (1,1,1,1)
        _SmallUVScaleA ("Small UV Scale A", Vector) = (1,1,1,1)
        _SmallUVOffsetR ("Small UV Offset R", Vector) = (1,1,1,1)
        _SmallUVOffsetG ("Small UV Offset G", Vector) = (1,1,1,1)
        _SmallUVOffsetB ("Small UV Offset B", Vector) = (1,1,1,1)
        _SmallUVOffsetA ("Small UV Offset A", Vector) = (1,1,1,1)
        _SmallTintR1 ("Small Tint R 1", Vector) = (1,1,1,1)
        _SmallTintR2 ("Small Tint R 2", Vector) = (1,1,1,1)
        _SmallTintR3 ("Small Tint R 3", Vector) = (1,1,1,1)
        _SmallTintR4 ("Small Tint R 4", Vector) = (1,1,1,1)
        _SmallTintG1 ("Small Tint G 1", Vector) = (1,1,1,1)
        _SmallTintG2 ("Small Tint G 2", Vector) = (1,1,1,1)
        _SmallTintG3 ("Small Tint G 3", Vector) = (1,1,1,1)
        _SmallTintG4 ("Small Tint G 4", Vector) = (1,1,1,1)
        _SmallTintB1 ("Small Tint B 1", Vector) = (1,1,1,1)
        _SmallTintB2 ("Small Tint B 2", Vector) = (1,1,1,1)
        _SmallTintB3 ("Small Tint B 3", Vector) = (1,1,1,1)
        _SmallTintB4 ("Small Tint B 4", Vector) = (1,1,1,1)
        _SmallTintA1 ("Small Tint A 1", Vector) = (1,1,1,1)
        _SmallTintA2 ("Small Tint A 2", Vector) = (1,1,1,1)
        _SmallTintA3 ("Small Tint A 3", Vector) = (1,1,1,1)
        _SmallTintA4 ("Small Tint A 4", Vector) = (1,1,1,1)
        _SmallBrightnessR ("Small Brightness R", Vector) = (0,0,0,0)
        _SmallBrightnessG ("Small Brightness G", Vector) = (0,0,0,0)
        _SmallBrightnessB ("Small Brightness B", Vector) = (0,0,0,0)
        _SmallBrightnessA ("Small Brightness A", Vector) = (0,0,0,0)
        _SmallContrastR ("Small Contrast R", Vector) = (1,1,1,1)
        _SmallContrastG ("Small Contrast G", Vector) = (1,1,1,1)
        _SmallContrastB ("Small Contrast B", Vector) = (1,1,1,1)
        _SmallContrastA ("Small Contrast A", Vector) = (1,1,1,1)
        _SmallSaturationR ("Small Saturation R", Vector) = (1,1,1,1)
        _SmallSaturationG ("Small Saturation G", Vector) = (1,1,1,1)
        _SmallSaturationB ("Small Saturation B", Vector) = (1,1,1,1)
        _SmallSaturationA ("Small Saturation A", Vector) = (1,1,1,1)
        _SmallNormalStrengthR ("Small Normal Strength R", Vector) = (1,1,1,1)
        _SmallNormalStrengthG ("Small Normal Strength G", Vector) = (1,1,1,1)
        _SmallNormalStrengthB ("Small Normal Strength B", Vector) = (1,1,1,1)
        _SmallNormalStrengthA ("Small Normal Strength A", Vector) = (1,1,1,1)
        _SmallGlossStrengthR ("Small Gloss Strength R", Vector) = (1,1,1,1)
        _SmallGlossStrengthG ("Small Gloss Strength G", Vector) = (1,1,1,1)
        _SmallGlossStrengthB ("Small Gloss Strength B", Vector) = (1,1,1,1)
        _SmallGlossStrengthA ("Small Gloss Strength A", Vector) = (1,1,1,1)
        _SmallMetallicStrengthR ("Small Metallic Strength R", Vector) = (0,0,0,0)
        _SmallMetallicStrengthG ("Small Metallic Strength G", Vector) = (0,0,0,0)
        _SmallMetallicStrengthB ("Small Metallic Strength B", Vector) = (0,0,0,0)
        _SmallMetallicStrengthA ("Small Metallic Strength A", Vector) = (0,0,0,0)
        _SmallEmissionStrengthR ("Small Emission Strength R", Vector) = (0,0,0,0)
        _SmallEmissionStrengthG ("Small Emission Strength G", Vector) = (0,0,0,0)
        _SmallEmissionStrengthB ("Small Emission Strength B", Vector) = (0,0,0,0)
        _SmallEmissionStrengthA ("Small Emission Strength A", Vector) = (0,0,0,0)
        _SmallEmissionColorR1 ("Small Emission Color R 1", Vector) = (1,1,1,1)
        _SmallEmissionColorR2 ("Small Emission Color R 2", Vector) = (1,1,1,1)
        _SmallEmissionColorR3 ("Small Emission Color R 3", Vector) = (1,1,1,1)
        _SmallEmissionColorR4 ("Small Emission Color R 4", Vector) = (1,1,1,1)
        _SmallEmissionColorG1 ("Small Emission Color G 1", Vector) = (1,1,1,1)
        _SmallEmissionColorG2 ("Small Emission Color G 2", Vector) = (1,1,1,1)
        _SmallEmissionColorG3 ("Small Emission Color G 3", Vector) = (1,1,1,1)
        _SmallEmissionColorG4 ("Small Emission Color G 4", Vector) = (1,1,1,1)
        _SmallEmissionColorB1 ("Small Emission Color B 1", Vector) = (1,1,1,1)
        _SmallEmissionColorB2 ("Small Emission Color B 2", Vector) = (1,1,1,1)
        _SmallEmissionColorB3 ("Small Emission Color B 3", Vector) = (1,1,1,1)
        _SmallEmissionColorB4 ("Small Emission Color B 4", Vector) = (1,1,1,1)
        _SmallEmissionColorA1 ("Small Emission Color A 1", Vector) = (1,1,1,1)
        _SmallEmissionColorA2 ("Small Emission Color A 2", Vector) = (1,1,1,1)
        _SmallEmissionColorA3 ("Small Emission Color A 3", Vector) = (1,1,1,1)
        _SmallEmissionColorA4 ("Small Emission Color A 4", Vector) = (1,1,1,1)
        _SmallAOStrengthR ("Small AO Strength R", Vector) = (1,1,1,1)
        _SmallAOStrengthG ("Small AO Strength G", Vector) = (1,1,1,1)
        _SmallAOStrengthB ("Small AO Strength B", Vector) = (1,1,1,1)
        _SmallAOStrengthA ("Small AO Strength A", Vector) = (1,1,1,1)
        _SmallDistanceResampleMaxR ("Small R Distance Resample Max", Vector) = (4,4,4,4)
        _SmallDistanceResampleMaxG ("Small G Distance Resample Max", Vector) = (4,4,4,4)
        _SmallDistanceResampleMaxB ("Small B Distance Resample Max", Vector) = (4,4,4,4)
        _SmallDistanceResampleMaxA ("Small A Distance Resample Max", Vector) = (4,4,4,4)
        _SmallEnableR ("Small Enable R", Vector) = (0,0,0,0)
        _SmallEnableG ("Small Enable G", Vector) = (0,0,0,0)
        _SmallEnableB ("Small Enable B", Vector) = (0,0,0,0)
        _SmallEnableA ("Small Enable A", Vector) = (0,0,0,0)
        _SmallSubzoneWeightR1 ("Small Subzone Weight R1", Vector) = (1,1,1,1)
        _SmallSubzoneWeightR2 ("Small Subzone Weight R2", Vector) = (1,1,1,1)
        _SmallSubzoneWeightR3 ("Small Subzone Weight R3", Vector) = (1,1,1,1)
        _SmallSubzoneWeightR4 ("Small Subzone Weight R4", Vector) = (1,1,1,1)
        _SmallSubzoneWeightG1 ("Small Subzone Weight G1", Vector) = (1,1,1,1)
        _SmallSubzoneWeightG2 ("Small Subzone Weight G2", Vector) = (1,1,1,1)
        _SmallSubzoneWeightG3 ("Small Subzone Weight G3", Vector) = (1,1,1,1)
        _SmallSubzoneWeightG4 ("Small Subzone Weight G4", Vector) = (1,1,1,1)
        _SmallSubzoneWeightB1 ("Small Subzone Weight B1", Vector) = (1,1,1,1)
        _SmallSubzoneWeightB2 ("Small Subzone Weight B2", Vector) = (1,1,1,1)
        _SmallSubzoneWeightB3 ("Small Subzone Weight B3", Vector) = (1,1,1,1)
        _SmallSubzoneWeightB4 ("Small Subzone Weight B4", Vector) = (1,1,1,1)
        _SmallSubzoneWeightA1 ("Small Subzone Weight A1", Vector) = (1,1,1,1)
        _SmallSubzoneWeightA2 ("Small Subzone Weight A2", Vector) = (1,1,1,1)
        _SmallSubzoneWeightA3 ("Small Subzone Weight A3", Vector) = (1,1,1,1)
        _SmallSubzoneWeightA4 ("Small Subzone Weight A4", Vector) = (1,1,1,1)
        _SmallSubzoneBrightnessR1 ("Small Subzone Brightness R1", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessR2 ("Small Subzone Brightness R2", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessR3 ("Small Subzone Brightness R3", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessR4 ("Small Subzone Brightness R4", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessG1 ("Small Subzone Brightness G1", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessG2 ("Small Subzone Brightness G2", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessG3 ("Small Subzone Brightness G3", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessG4 ("Small Subzone Brightness G4", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessB1 ("Small Subzone Brightness B1", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessB2 ("Small Subzone Brightness B2", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessB3 ("Small Subzone Brightness B3", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessB4 ("Small Subzone Brightness B4", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessA1 ("Small Subzone Brightness A1", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessA2 ("Small Subzone Brightness A2", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessA3 ("Small Subzone Brightness A3", Vector) = (0,0,0,0)
        _SmallSubzoneBrightnessA4 ("Small Subzone Brightness A4", Vector) = (0,0,0,0)
        _SmallSubzoneTintR1_R ("Small Subzone Tint R1 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintR1_G ("Small Subzone Tint R1 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintR1_B ("Small Subzone Tint R1 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintR1_A ("Small Subzone Tint R1 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintR2_R ("Small Subzone Tint R2 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintR2_G ("Small Subzone Tint R2 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintR2_B ("Small Subzone Tint R2 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintR2_A ("Small Subzone Tint R2 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintR3_R ("Small Subzone Tint R3 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintR3_G ("Small Subzone Tint R3 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintR3_B ("Small Subzone Tint R3 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintR3_A ("Small Subzone Tint R3 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintR4_R ("Small Subzone Tint R4 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintR4_G ("Small Subzone Tint R4 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintR4_B ("Small Subzone Tint R4 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintR4_A ("Small Subzone Tint R4 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintG1_R ("Small Subzone Tint G1 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintG1_G ("Small Subzone Tint G1 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintG1_B ("Small Subzone Tint G1 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintG1_A ("Small Subzone Tint G1 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintG2_R ("Small Subzone Tint G2 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintG2_G ("Small Subzone Tint G2 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintG2_B ("Small Subzone Tint G2 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintG2_A ("Small Subzone Tint G2 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintG3_R ("Small Subzone Tint G3 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintG3_G ("Small Subzone Tint G3 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintG3_B ("Small Subzone Tint G3 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintG3_A ("Small Subzone Tint G3 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintG4_R ("Small Subzone Tint G4 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintG4_G ("Small Subzone Tint G4 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintG4_B ("Small Subzone Tint G4 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintG4_A ("Small Subzone Tint G4 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintB1_R ("Small Subzone Tint B1 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintB1_G ("Small Subzone Tint B1 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintB1_B ("Small Subzone Tint B1 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintB1_A ("Small Subzone Tint B1 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintB2_R ("Small Subzone Tint B2 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintB2_G ("Small Subzone Tint B2 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintB2_B ("Small Subzone Tint B2 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintB2_A ("Small Subzone Tint B2 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintB3_R ("Small Subzone Tint B3 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintB3_G ("Small Subzone Tint B3 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintB3_B ("Small Subzone Tint B3 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintB3_A ("Small Subzone Tint B3 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintB4_R ("Small Subzone Tint B4 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintB4_G ("Small Subzone Tint B4 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintB4_B ("Small Subzone Tint B4 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintB4_A ("Small Subzone Tint B4 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintA1_R ("Small Subzone Tint A1 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintA1_G ("Small Subzone Tint A1 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintA1_B ("Small Subzone Tint A1 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintA1_A ("Small Subzone Tint A1 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintA2_R ("Small Subzone Tint A2 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintA2_G ("Small Subzone Tint A2 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintA2_B ("Small Subzone Tint A2 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintA2_A ("Small Subzone Tint A2 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintA3_R ("Small Subzone Tint A1 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintA3_G ("Small Subzone Tint A1 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintA3_B ("Small Subzone Tint A1 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintA3_A ("Small Subzone Tint A1 - A", Vector) = (1,1,1,1)
        _SmallSubzoneTintA4_R ("Small Subzone Tint A1 - R", Vector) = (1,1,1,1)
        _SmallSubzoneTintA4_G ("Small Subzone Tint A1 - G", Vector) = (1,1,1,1)
        _SmallSubzoneTintA4_B ("Small Subzone Tint A1 - B", Vector) = (1,1,1,1)
        _SmallSubzoneTintA4_A ("Small Subzone Tint A1 - A", Vector) = (1,1,1,1)
        _HeightblendFactor ("Height Blend Factor", Vector) = (0.02,0.02,0.02,0.02)
        _DistanceResampleDistances ("Distance Resample Distances", Vector) = (0,0,0,0)
        _DistanceResampleUVScales ("Distance Resample UV Scales", Vector) = (1,1,1,1)
        _DistanceResampleAlbedoOpacity ("Distance Resample Albedo Opacity", Vector) = (1,1,1,1)
        _DistanceResampleNormalOpacity ("Distance Resample Normal Opacity", Vector) = (1,1,1,1)
        _GlobalBlend ("Global Blend", Vector) = (1,1,1,1)
        _AlphaToHeightFadeParams ("Alpha to Height Fade", Vector) = (1,1,1,1)
        [HideInInspector] _DistanceResampleFades ("Distance Resample Fades", Vector) = (1,1,1,1)
        [HideInInspector] _DistanceResampleFadeRangesPos ("Distance Resample Fade Ranges Pos", Vector) = (1,1,1,1)
        [HideInInspector] _DistanceResampleFadeRangesNeg ("Distance Resample Fade Ranges Ned", Vector) = (1,1,1,1)
        _StochasticScale ("Scale", Range(0.25, 2)) = 1
        _ShorelineTex ("Shoreline", 2D) = "white" {}
        [HideInInspector] _LocalSpacePrepassTex0 ("Local Space Prepass Texture 0", 2D) = "white" {}
        [HideInInspector] _LocalSpacePrepassTex1 ("Local Space Prepass Texture 1", 2D) = "white" {}
        [HideInInspector] _LocalSpacePrepassTex2 ("Local Space Prepass Texture 2", 2D) = "white" {}
        [HideInInspector] _LocalSpacePrepassTex3 ("Local Space Prepass Texture 3", 2D) = "white" {}
        [HideInInspector] _LocalSpacePrepassTex4 ("Local Space Prepass Texture 4", 2D) = "white" {}
        [ToggleOff(LOW_QUALITY)] _HighQualityEnabled ("High Quality", Float) = 1
    }
    //DummyShaderTextExporter
    SubShader{
        Tags { "RenderType" = "Opaque" }
        LOD 200
        CGPROGRAM
#pragma surface surf Standard
#pragma target 3.0
        sampler2D _AlbedoScaledTex;

        struct Input
        {
            float2 uv_MainTex;
        };

        void surf(Input IN, inout SurfaceOutputStandard o)
        {
            fixed4 c = tex2D(_AlbedoScaledTex, IN.uv_MainTex);
            o.Albedo = c.rgb;
            o.Alpha = 1.0;
        }
        ENDCG
    }
}
